// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protos/server.proto
#ifndef GRPC_protos_2fserver_2eproto__INCLUDED
#define GRPC_protos_2fserver_2eproto__INCLUDED

#include "protos/server.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace MyVocaloid {

class Vocaloid final {
 public:
  static constexpr char const* service_full_name() {
    return "MyVocaloid.Vocaloid";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Sing(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest& request, ::MyVocaloid::SingReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MyVocaloid::SingReply>> AsyncSing(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MyVocaloid::SingReply>>(AsyncSingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MyVocaloid::SingReply>> PrepareAsyncSing(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MyVocaloid::SingReply>>(PrepareAsyncSingRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Sing(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest* request, ::MyVocaloid::SingReply* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MyVocaloid::SingReply>* AsyncSingRaw(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MyVocaloid::SingReply>* PrepareAsyncSingRaw(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Sing(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest& request, ::MyVocaloid::SingReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MyVocaloid::SingReply>> AsyncSing(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MyVocaloid::SingReply>>(AsyncSingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MyVocaloid::SingReply>> PrepareAsyncSing(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MyVocaloid::SingReply>>(PrepareAsyncSingRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Sing(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest* request, ::MyVocaloid::SingReply* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::MyVocaloid::SingReply>* AsyncSingRaw(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MyVocaloid::SingReply>* PrepareAsyncSingRaw(::grpc::ClientContext* context, const ::MyVocaloid::SingRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Sing_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Sing(::grpc::ServerContext* context, const ::MyVocaloid::SingRequest* request, ::MyVocaloid::SingReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Sing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Sing() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Sing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sing(::grpc::ServerContext* context, const ::MyVocaloid::SingRequest* request, ::MyVocaloid::SingReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSing(::grpc::ServerContext* context, ::MyVocaloid::SingRequest* request, ::grpc::ServerAsyncResponseWriter< ::MyVocaloid::SingReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Sing<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Sing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Sing() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Sing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sing(::grpc::ServerContext* context, const ::MyVocaloid::SingRequest* request, ::MyVocaloid::SingReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Sing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Sing() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Sing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sing(::grpc::ServerContext* context, const ::MyVocaloid::SingRequest* request, ::MyVocaloid::SingReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Sing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Sing() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::MyVocaloid::SingRequest, ::MyVocaloid::SingReply>(std::bind(&WithStreamedUnaryMethod_Sing<BaseClass>::StreamedSing, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Sing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Sing(::grpc::ServerContext* context, const ::MyVocaloid::SingRequest* request, ::MyVocaloid::SingReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MyVocaloid::SingRequest,::MyVocaloid::SingReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Sing<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Sing<Service > StreamedService;
};

}  // namespace MyVocaloid


#endif  // GRPC_protos_2fserver_2eproto__INCLUDED
