// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/server.proto

#include "protos/server.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_protos_2fserver_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_protos_2fserver_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Note;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_protos_2fserver_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ReplyChunk;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_protos_2fserver_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ReplyHeader;
}  // namespace protobuf_protos_2fserver_2eproto
namespace MyVocaloid {
class NoteDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Note>
      _instance;
} _Note_default_instance_;
class SingRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SingRequest>
      _instance;
} _SingRequest_default_instance_;
class ReplyHeaderDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReplyHeader>
      _instance;
} _ReplyHeader_default_instance_;
class ReplyChunkDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReplyChunk>
      _instance;
} _ReplyChunk_default_instance_;
class SingReplyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SingReply>
      _instance;
  const ::MyVocaloid::ReplyHeader* header_;
  const ::MyVocaloid::ReplyChunk* chunk_;
} _SingReply_default_instance_;
}  // namespace MyVocaloid
namespace protobuf_protos_2fserver_2eproto {
static void InitDefaultsNote() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyVocaloid::_Note_default_instance_;
    new (ptr) ::MyVocaloid::Note();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyVocaloid::Note::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Note =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNote}, {}};

static void InitDefaultsSingRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyVocaloid::_SingRequest_default_instance_;
    new (ptr) ::MyVocaloid::SingRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyVocaloid::SingRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_SingRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsSingRequest}, {
      &protobuf_protos_2fserver_2eproto::scc_info_Note.base,}};

static void InitDefaultsReplyHeader() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyVocaloid::_ReplyHeader_default_instance_;
    new (ptr) ::MyVocaloid::ReplyHeader();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyVocaloid::ReplyHeader::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReplyHeader =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReplyHeader}, {}};

static void InitDefaultsReplyChunk() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyVocaloid::_ReplyChunk_default_instance_;
    new (ptr) ::MyVocaloid::ReplyChunk();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyVocaloid::ReplyChunk::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReplyChunk =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReplyChunk}, {}};

static void InitDefaultsSingReply() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyVocaloid::_SingReply_default_instance_;
    new (ptr) ::MyVocaloid::SingReply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyVocaloid::SingReply::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_SingReply =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsSingReply}, {
      &protobuf_protos_2fserver_2eproto::scc_info_ReplyHeader.base,
      &protobuf_protos_2fserver_2eproto::scc_info_ReplyChunk.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Note.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SingRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReplyHeader.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReplyChunk.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SingReply.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::Note, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::Note, note_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::Note, start_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::Note, duration_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::SingRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::SingRequest, bpm_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::SingRequest, lyrics_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::SingRequest, notes_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::SingRequest, bank_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::ReplyHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::ReplyHeader, result_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::ReplyHeader, message_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::ReplyChunk, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::ReplyChunk, data_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::SingReply, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::SingReply, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(::MyVocaloid::SingReplyDefaultTypeInternal, header_),
  offsetof(::MyVocaloid::SingReplyDefaultTypeInternal, chunk_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyVocaloid::SingReply, ReplyData_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::MyVocaloid::Note)},
  { 8, -1, sizeof(::MyVocaloid::SingRequest)},
  { 17, -1, sizeof(::MyVocaloid::ReplyHeader)},
  { 24, -1, sizeof(::MyVocaloid::ReplyChunk)},
  { 30, -1, sizeof(::MyVocaloid::SingReply)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::MyVocaloid::_Note_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::MyVocaloid::_SingRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::MyVocaloid::_ReplyHeader_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::MyVocaloid::_ReplyChunk_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::MyVocaloid::_SingReply_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "protos/server.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023protos/server.proto\022\nMyVocaloid\"5\n\004Not"
      "e\022\014\n\004note\030\001 \001(\005\022\r\n\005start\030\002 \001(\005\022\020\n\010durati"
      "on\030\003 \001(\005\"Y\n\013SingRequest\022\013\n\003bpm\030\001 \001(\005\022\016\n\006"
      "lyrics\030\002 \001(\t\022\037\n\005notes\030\003 \003(\0132\020.MyVocaloid"
      ".Note\022\014\n\004bank\030\004 \001(\005\".\n\013ReplyHeader\022\016\n\006re"
      "sult\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\"\032\n\nReplyChun"
      "k\022\014\n\004data\030\001 \001(\014\"l\n\tSingReply\022)\n\006header\030\001"
      " \001(\0132\027.MyVocaloid.ReplyHeaderH\000\022\'\n\005chunk"
      "\030\002 \001(\0132\026.MyVocaloid.ReplyChunkH\000B\013\n\tRepl"
      "yData2F\n\010Vocaloid\022:\n\004Sing\022\027.MyVocaloid.S"
      "ingRequest\032\025.MyVocaloid.SingReply\"\0000\001b\006p"
      "roto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 445);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protos/server.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_protos_2fserver_2eproto
namespace MyVocaloid {

// ===================================================================

void Note::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Note::kNoteFieldNumber;
const int Note::kStartFieldNumber;
const int Note::kDurationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Note::Note()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_protos_2fserver_2eproto::scc_info_Note.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:MyVocaloid.Note)
}
Note::Note(const Note& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&note_, &from.note_,
    static_cast<size_t>(reinterpret_cast<char*>(&duration_) -
    reinterpret_cast<char*>(&note_)) + sizeof(duration_));
  // @@protoc_insertion_point(copy_constructor:MyVocaloid.Note)
}

void Note::SharedCtor() {
  ::memset(&note_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&duration_) -
      reinterpret_cast<char*>(&note_)) + sizeof(duration_));
}

Note::~Note() {
  // @@protoc_insertion_point(destructor:MyVocaloid.Note)
  SharedDtor();
}

void Note::SharedDtor() {
}

void Note::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Note::descriptor() {
  ::protobuf_protos_2fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2fserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Note& Note::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_protos_2fserver_2eproto::scc_info_Note.base);
  return *internal_default_instance();
}


void Note::Clear() {
// @@protoc_insertion_point(message_clear_start:MyVocaloid.Note)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&note_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&duration_) -
      reinterpret_cast<char*>(&note_)) + sizeof(duration_));
  _internal_metadata_.Clear();
}

bool Note::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MyVocaloid.Note)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 note = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &note_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 start = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &start_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 duration = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &duration_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MyVocaloid.Note)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MyVocaloid.Note)
  return false;
#undef DO_
}

void Note::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MyVocaloid.Note)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 note = 1;
  if (this->note() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->note(), output);
  }

  // int32 start = 2;
  if (this->start() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->start(), output);
  }

  // int32 duration = 3;
  if (this->duration() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->duration(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:MyVocaloid.Note)
}

::google::protobuf::uint8* Note::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MyVocaloid.Note)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 note = 1;
  if (this->note() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->note(), target);
  }

  // int32 start = 2;
  if (this->start() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->start(), target);
  }

  // int32 duration = 3;
  if (this->duration() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->duration(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyVocaloid.Note)
  return target;
}

size_t Note::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyVocaloid.Note)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 note = 1;
  if (this->note() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->note());
  }

  // int32 start = 2;
  if (this->start() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->start());
  }

  // int32 duration = 3;
  if (this->duration() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->duration());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Note::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyVocaloid.Note)
  GOOGLE_DCHECK_NE(&from, this);
  const Note* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Note>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyVocaloid.Note)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyVocaloid.Note)
    MergeFrom(*source);
  }
}

void Note::MergeFrom(const Note& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyVocaloid.Note)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.note() != 0) {
    set_note(from.note());
  }
  if (from.start() != 0) {
    set_start(from.start());
  }
  if (from.duration() != 0) {
    set_duration(from.duration());
  }
}

void Note::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyVocaloid.Note)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Note::CopyFrom(const Note& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyVocaloid.Note)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Note::IsInitialized() const {
  return true;
}

void Note::Swap(Note* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Note::InternalSwap(Note* other) {
  using std::swap;
  swap(note_, other->note_);
  swap(start_, other->start_);
  swap(duration_, other->duration_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Note::GetMetadata() const {
  protobuf_protos_2fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2fserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SingRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SingRequest::kBpmFieldNumber;
const int SingRequest::kLyricsFieldNumber;
const int SingRequest::kNotesFieldNumber;
const int SingRequest::kBankFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SingRequest::SingRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_protos_2fserver_2eproto::scc_info_SingRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:MyVocaloid.SingRequest)
}
SingRequest::SingRequest(const SingRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      notes_(from.notes_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  lyrics_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.lyrics().size() > 0) {
    lyrics_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lyrics_);
  }
  ::memcpy(&bpm_, &from.bpm_,
    static_cast<size_t>(reinterpret_cast<char*>(&bank_) -
    reinterpret_cast<char*>(&bpm_)) + sizeof(bank_));
  // @@protoc_insertion_point(copy_constructor:MyVocaloid.SingRequest)
}

void SingRequest::SharedCtor() {
  lyrics_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&bpm_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&bank_) -
      reinterpret_cast<char*>(&bpm_)) + sizeof(bank_));
}

SingRequest::~SingRequest() {
  // @@protoc_insertion_point(destructor:MyVocaloid.SingRequest)
  SharedDtor();
}

void SingRequest::SharedDtor() {
  lyrics_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SingRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SingRequest::descriptor() {
  ::protobuf_protos_2fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2fserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SingRequest& SingRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_protos_2fserver_2eproto::scc_info_SingRequest.base);
  return *internal_default_instance();
}


void SingRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:MyVocaloid.SingRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  notes_.Clear();
  lyrics_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&bpm_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&bank_) -
      reinterpret_cast<char*>(&bpm_)) + sizeof(bank_));
  _internal_metadata_.Clear();
}

bool SingRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MyVocaloid.SingRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 bpm = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &bpm_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string lyrics = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_lyrics()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->lyrics().data(), static_cast<int>(this->lyrics().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MyVocaloid.SingRequest.lyrics"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .MyVocaloid.Note notes = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_notes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 bank = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &bank_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MyVocaloid.SingRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MyVocaloid.SingRequest)
  return false;
#undef DO_
}

void SingRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MyVocaloid.SingRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 bpm = 1;
  if (this->bpm() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->bpm(), output);
  }

  // string lyrics = 2;
  if (this->lyrics().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->lyrics().data(), static_cast<int>(this->lyrics().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MyVocaloid.SingRequest.lyrics");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->lyrics(), output);
  }

  // repeated .MyVocaloid.Note notes = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->notes_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->notes(static_cast<int>(i)),
      output);
  }

  // int32 bank = 4;
  if (this->bank() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->bank(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:MyVocaloid.SingRequest)
}

::google::protobuf::uint8* SingRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MyVocaloid.SingRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 bpm = 1;
  if (this->bpm() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->bpm(), target);
  }

  // string lyrics = 2;
  if (this->lyrics().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->lyrics().data(), static_cast<int>(this->lyrics().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MyVocaloid.SingRequest.lyrics");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->lyrics(), target);
  }

  // repeated .MyVocaloid.Note notes = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->notes_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->notes(static_cast<int>(i)), deterministic, target);
  }

  // int32 bank = 4;
  if (this->bank() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->bank(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyVocaloid.SingRequest)
  return target;
}

size_t SingRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyVocaloid.SingRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .MyVocaloid.Note notes = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->notes_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->notes(static_cast<int>(i)));
    }
  }

  // string lyrics = 2;
  if (this->lyrics().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->lyrics());
  }

  // int32 bpm = 1;
  if (this->bpm() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->bpm());
  }

  // int32 bank = 4;
  if (this->bank() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->bank());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SingRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyVocaloid.SingRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const SingRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SingRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyVocaloid.SingRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyVocaloid.SingRequest)
    MergeFrom(*source);
  }
}

void SingRequest::MergeFrom(const SingRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyVocaloid.SingRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  notes_.MergeFrom(from.notes_);
  if (from.lyrics().size() > 0) {

    lyrics_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lyrics_);
  }
  if (from.bpm() != 0) {
    set_bpm(from.bpm());
  }
  if (from.bank() != 0) {
    set_bank(from.bank());
  }
}

void SingRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyVocaloid.SingRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SingRequest::CopyFrom(const SingRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyVocaloid.SingRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SingRequest::IsInitialized() const {
  return true;
}

void SingRequest::Swap(SingRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SingRequest::InternalSwap(SingRequest* other) {
  using std::swap;
  CastToBase(&notes_)->InternalSwap(CastToBase(&other->notes_));
  lyrics_.Swap(&other->lyrics_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(bpm_, other->bpm_);
  swap(bank_, other->bank_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SingRequest::GetMetadata() const {
  protobuf_protos_2fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2fserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReplyHeader::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReplyHeader::kResultFieldNumber;
const int ReplyHeader::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReplyHeader::ReplyHeader()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_protos_2fserver_2eproto::scc_info_ReplyHeader.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:MyVocaloid.ReplyHeader)
}
ReplyHeader::ReplyHeader(const ReplyHeader& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  result_ = from.result_;
  // @@protoc_insertion_point(copy_constructor:MyVocaloid.ReplyHeader)
}

void ReplyHeader::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  result_ = 0;
}

ReplyHeader::~ReplyHeader() {
  // @@protoc_insertion_point(destructor:MyVocaloid.ReplyHeader)
  SharedDtor();
}

void ReplyHeader::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ReplyHeader::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReplyHeader::descriptor() {
  ::protobuf_protos_2fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2fserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReplyHeader& ReplyHeader::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_protos_2fserver_2eproto::scc_info_ReplyHeader.base);
  return *internal_default_instance();
}


void ReplyHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:MyVocaloid.ReplyHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  result_ = 0;
  _internal_metadata_.Clear();
}

bool ReplyHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MyVocaloid.ReplyHeader)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 result = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string message = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MyVocaloid.ReplyHeader.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MyVocaloid.ReplyHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MyVocaloid.ReplyHeader)
  return false;
#undef DO_
}

void ReplyHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MyVocaloid.ReplyHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  // string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MyVocaloid.ReplyHeader.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->message(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:MyVocaloid.ReplyHeader)
}

::google::protobuf::uint8* ReplyHeader::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MyVocaloid.ReplyHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  // string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MyVocaloid.ReplyHeader.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->message(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyVocaloid.ReplyHeader)
  return target;
}

size_t ReplyHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyVocaloid.ReplyHeader)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string message = 2;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // int32 result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReplyHeader::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyVocaloid.ReplyHeader)
  GOOGLE_DCHECK_NE(&from, this);
  const ReplyHeader* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReplyHeader>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyVocaloid.ReplyHeader)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyVocaloid.ReplyHeader)
    MergeFrom(*source);
  }
}

void ReplyHeader::MergeFrom(const ReplyHeader& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyVocaloid.ReplyHeader)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.result() != 0) {
    set_result(from.result());
  }
}

void ReplyHeader::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyVocaloid.ReplyHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReplyHeader::CopyFrom(const ReplyHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyVocaloid.ReplyHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReplyHeader::IsInitialized() const {
  return true;
}

void ReplyHeader::Swap(ReplyHeader* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReplyHeader::InternalSwap(ReplyHeader* other) {
  using std::swap;
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(result_, other->result_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReplyHeader::GetMetadata() const {
  protobuf_protos_2fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2fserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReplyChunk::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReplyChunk::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReplyChunk::ReplyChunk()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_protos_2fserver_2eproto::scc_info_ReplyChunk.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:MyVocaloid.ReplyChunk)
}
ReplyChunk::ReplyChunk(const ReplyChunk& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.data().size() > 0) {
    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  // @@protoc_insertion_point(copy_constructor:MyVocaloid.ReplyChunk)
}

void ReplyChunk::SharedCtor() {
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ReplyChunk::~ReplyChunk() {
  // @@protoc_insertion_point(destructor:MyVocaloid.ReplyChunk)
  SharedDtor();
}

void ReplyChunk::SharedDtor() {
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ReplyChunk::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReplyChunk::descriptor() {
  ::protobuf_protos_2fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2fserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReplyChunk& ReplyChunk::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_protos_2fserver_2eproto::scc_info_ReplyChunk.base);
  return *internal_default_instance();
}


void ReplyChunk::Clear() {
// @@protoc_insertion_point(message_clear_start:MyVocaloid.ReplyChunk)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ReplyChunk::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MyVocaloid.ReplyChunk)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes data = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MyVocaloid.ReplyChunk)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MyVocaloid.ReplyChunk)
  return false;
#undef DO_
}

void ReplyChunk::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MyVocaloid.ReplyChunk)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes data = 1;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->data(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:MyVocaloid.ReplyChunk)
}

::google::protobuf::uint8* ReplyChunk::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MyVocaloid.ReplyChunk)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes data = 1;
  if (this->data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->data(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyVocaloid.ReplyChunk)
  return target;
}

size_t ReplyChunk::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyVocaloid.ReplyChunk)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes data = 1;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReplyChunk::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyVocaloid.ReplyChunk)
  GOOGLE_DCHECK_NE(&from, this);
  const ReplyChunk* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReplyChunk>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyVocaloid.ReplyChunk)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyVocaloid.ReplyChunk)
    MergeFrom(*source);
  }
}

void ReplyChunk::MergeFrom(const ReplyChunk& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyVocaloid.ReplyChunk)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
}

void ReplyChunk::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyVocaloid.ReplyChunk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReplyChunk::CopyFrom(const ReplyChunk& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyVocaloid.ReplyChunk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReplyChunk::IsInitialized() const {
  return true;
}

void ReplyChunk::Swap(ReplyChunk* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReplyChunk::InternalSwap(ReplyChunk* other) {
  using std::swap;
  data_.Swap(&other->data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReplyChunk::GetMetadata() const {
  protobuf_protos_2fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2fserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SingReply::InitAsDefaultInstance() {
  ::MyVocaloid::_SingReply_default_instance_.header_ = const_cast< ::MyVocaloid::ReplyHeader*>(
      ::MyVocaloid::ReplyHeader::internal_default_instance());
  ::MyVocaloid::_SingReply_default_instance_.chunk_ = const_cast< ::MyVocaloid::ReplyChunk*>(
      ::MyVocaloid::ReplyChunk::internal_default_instance());
}
void SingReply::set_allocated_header(::MyVocaloid::ReplyHeader* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_ReplyData();
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    set_has_header();
    ReplyData_.header_ = header;
  }
  // @@protoc_insertion_point(field_set_allocated:MyVocaloid.SingReply.header)
}
void SingReply::set_allocated_chunk(::MyVocaloid::ReplyChunk* chunk) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_ReplyData();
  if (chunk) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      chunk = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, chunk, submessage_arena);
    }
    set_has_chunk();
    ReplyData_.chunk_ = chunk;
  }
  // @@protoc_insertion_point(field_set_allocated:MyVocaloid.SingReply.chunk)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SingReply::kHeaderFieldNumber;
const int SingReply::kChunkFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SingReply::SingReply()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_protos_2fserver_2eproto::scc_info_SingReply.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:MyVocaloid.SingReply)
}
SingReply::SingReply(const SingReply& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_ReplyData();
  switch (from.ReplyData_case()) {
    case kHeader: {
      mutable_header()->::MyVocaloid::ReplyHeader::MergeFrom(from.header());
      break;
    }
    case kChunk: {
      mutable_chunk()->::MyVocaloid::ReplyChunk::MergeFrom(from.chunk());
      break;
    }
    case REPLYDATA_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:MyVocaloid.SingReply)
}

void SingReply::SharedCtor() {
  clear_has_ReplyData();
}

SingReply::~SingReply() {
  // @@protoc_insertion_point(destructor:MyVocaloid.SingReply)
  SharedDtor();
}

void SingReply::SharedDtor() {
  if (has_ReplyData()) {
    clear_ReplyData();
  }
}

void SingReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SingReply::descriptor() {
  ::protobuf_protos_2fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2fserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SingReply& SingReply::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_protos_2fserver_2eproto::scc_info_SingReply.base);
  return *internal_default_instance();
}


void SingReply::clear_ReplyData() {
// @@protoc_insertion_point(one_of_clear_start:MyVocaloid.SingReply)
  switch (ReplyData_case()) {
    case kHeader: {
      delete ReplyData_.header_;
      break;
    }
    case kChunk: {
      delete ReplyData_.chunk_;
      break;
    }
    case REPLYDATA_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = REPLYDATA_NOT_SET;
}


void SingReply::Clear() {
// @@protoc_insertion_point(message_clear_start:MyVocaloid.SingReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_ReplyData();
  _internal_metadata_.Clear();
}

bool SingReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MyVocaloid.SingReply)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .MyVocaloid.ReplyHeader header = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .MyVocaloid.ReplyChunk chunk = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_chunk()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MyVocaloid.SingReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MyVocaloid.SingReply)
  return false;
#undef DO_
}

void SingReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MyVocaloid.SingReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .MyVocaloid.ReplyHeader header = 1;
  if (has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_header(), output);
  }

  // .MyVocaloid.ReplyChunk chunk = 2;
  if (has_chunk()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_chunk(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:MyVocaloid.SingReply)
}

::google::protobuf::uint8* SingReply::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MyVocaloid.SingReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .MyVocaloid.ReplyHeader header = 1;
  if (has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_header(), deterministic, target);
  }

  // .MyVocaloid.ReplyChunk chunk = 2;
  if (has_chunk()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_chunk(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyVocaloid.SingReply)
  return target;
}

size_t SingReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyVocaloid.SingReply)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  switch (ReplyData_case()) {
    // .MyVocaloid.ReplyHeader header = 1;
    case kHeader: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *ReplyData_.header_);
      break;
    }
    // .MyVocaloid.ReplyChunk chunk = 2;
    case kChunk: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *ReplyData_.chunk_);
      break;
    }
    case REPLYDATA_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SingReply::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyVocaloid.SingReply)
  GOOGLE_DCHECK_NE(&from, this);
  const SingReply* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SingReply>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyVocaloid.SingReply)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyVocaloid.SingReply)
    MergeFrom(*source);
  }
}

void SingReply::MergeFrom(const SingReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyVocaloid.SingReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.ReplyData_case()) {
    case kHeader: {
      mutable_header()->::MyVocaloid::ReplyHeader::MergeFrom(from.header());
      break;
    }
    case kChunk: {
      mutable_chunk()->::MyVocaloid::ReplyChunk::MergeFrom(from.chunk());
      break;
    }
    case REPLYDATA_NOT_SET: {
      break;
    }
  }
}

void SingReply::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyVocaloid.SingReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SingReply::CopyFrom(const SingReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyVocaloid.SingReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SingReply::IsInitialized() const {
  return true;
}

void SingReply::Swap(SingReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SingReply::InternalSwap(SingReply* other) {
  using std::swap;
  swap(ReplyData_, other->ReplyData_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SingReply::GetMetadata() const {
  protobuf_protos_2fserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2fserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace MyVocaloid
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::MyVocaloid::Note* Arena::CreateMaybeMessage< ::MyVocaloid::Note >(Arena* arena) {
  return Arena::CreateInternal< ::MyVocaloid::Note >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::MyVocaloid::SingRequest* Arena::CreateMaybeMessage< ::MyVocaloid::SingRequest >(Arena* arena) {
  return Arena::CreateInternal< ::MyVocaloid::SingRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::MyVocaloid::ReplyHeader* Arena::CreateMaybeMessage< ::MyVocaloid::ReplyHeader >(Arena* arena) {
  return Arena::CreateInternal< ::MyVocaloid::ReplyHeader >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::MyVocaloid::ReplyChunk* Arena::CreateMaybeMessage< ::MyVocaloid::ReplyChunk >(Arena* arena) {
  return Arena::CreateInternal< ::MyVocaloid::ReplyChunk >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::MyVocaloid::SingReply* Arena::CreateMaybeMessage< ::MyVocaloid::SingReply >(Arena* arena) {
  return Arena::CreateInternal< ::MyVocaloid::SingReply >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
